name: Update copyright year(s) in license file

on:
  schedule:
    - cron: "00 1 1 1 *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - uses: FantasticFiasco/action-update-license-year@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: |
          README.md
          ./**/*.js
        branchName: license/{{currentYear}}
        commitTitle: update license
        commitBody: Let's keep legal happy.
        prTitle: Update copyright years in README.md and source files
        prBody: It's that time of the year, let's update the license.
